### PR TITLE
Ensure local TDS is default

### PR DESCRIPTION
**Pull request by fivegrant**
This PR adds missing environment variables to `env.sample` and documents that the user should copy this over in the README. With the workflow update, `TDS_URL` and `SIMSERVICE_TDS_URL` are now expected in `.env`, however, these are not in `env.sample`. I've set the default to the 'simulation-integration' data service since that's the one people will be using the most

### CODE REVIEW

**Review by Sorrento110 — APPROVED** [review]
Works well for me!

**Review by sabinala — COMMENTED** [review]
Worked for me! Petrinets are green checks, stockflow and regnets are x's, as expected.

**Comment by sabinala** [comment]
@fivegrant Do you need to add `docker compose down` to the READme?

**Comment by fivegrant** [comment]
added. thanks @sabinala !

**Pull request merged**
