### PR TITLE
Adding gold standard regnet AMRs

### LINKED ISSUE #33: Add working regnet AMRs
Adding a set of regnet model examples that are known to work properly (i.e., can be sampled and simulated) and include uncertainty in parameters as well as observables. This set of models should serve as the gold-standard set of regnet models for testing.

### PR DESCRIPTION
**Pull request by sabinala**
This PR adds five gold-standard example AMRs for regnets. They are all of Lotka-Volterra type, and have uncertainty in parameters, initial conditions, and observables.

Closes #33

### CODE REVIEW

**Comment by fivegrant** [comment]
added @jClugstor as a reviewer as well since these will be used for the SciML Service as well

**Review by fivegrant — APPROVED** [review]
tested seeding and it worked for me! @sabinala it may make sense though to merge this after @jClugstor has had a chance to look at it.

**Comment by sabinala** [comment]
Will do!

**Review by jClugstor — APPROVED** [review]
Looks good to me!

**Pull request merged**
